version: '3'
services:
  psn-service:
    build: .
    volumes:
      - ../output:/app/output
    environment:
      - NPSSO=${NPSSO}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "8080:8080"

  psn-frontend:
    build: 
      context: ./vite-frontend
      dockerfile: Dockerfile
    environment:
      - VITE_ALLOWED_ORIGINS=${VITE_ALLOWED_ORIGINS}
    ports:
      - "5173:5173"
    depends_on:
      - psn-service