version: '3'
services:
  psn-backend:
    restart: unless-stopped
    mem_limit: 512m
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    volumes:
      - psn-output-data:/app/output
    environment:
      - NPSSO=${NPSSO}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - NTFY_TOPIC_URL=${NTFY_TOPIC_URL:-}
      - HEALTHCHECKS_LIVENESS_URL=${HEALTHCHECKS_LIVENESS_URL:-}
      - HEALTHCHECKS_SUCCESS_URL=${HEALTHCHECKS_SUCCESS_URL:-}
    ports:
      - "8080:8080"

  psn-frontend:
    restart: unless-stopped
    mem_limit: 384m
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    environment:
      - VITE_ALLOWED_ORIGINS=${VITE_ALLOWED_ORIGINS}
    ports:
      - "5173:5173"
    depends_on:
      - psn-backend

volumes:
  psn-output-data:
    driver: local
    name: psn-output-data
